# Model
id: "llama3-1-8b-26"
model_name_or_path: "/kaggle/input/notebooks/diansss/llama-loader/Llama-3.1-8B-Instruct"
behavior: "survival-instinct"
layer: [26]
total_layer: 32

# Vector
vec_dir: "caa/pretrained_vector/survival-instinct/llama-3/all"
answer_dir: "caa/generation_results/survival-instinct/llama-3/26"
apply_type: "base"