# Model
id: "mistral-7b-16"
model_name_or_path: "/kaggle/input/notebooks/diansss/mistral-loader/Mistral-7B-Instruct-v0.3"
behavior: "corrigible-less"
layer: [16]
total_layer: 32

# Vector
vec_dir: "caa/pretrained_vector/corrigible-less/mistral/all"
answer_dir: "caa/generation_results/corrigible-less/mistral/16"
apply_type: "base"