# Model
id: "mistral-7b-6"
model_name_or_path: "/kaggle/input/notebooks/dadangkw/mistral-loader/Mistral-7B-Instruct-v0.3"
behavior: "corrigible-less"
layer: [6]
total_layer: 32

# Vector
vec_dir: "caa/pretrained_vector/corrigible-less/mistral/all"
answer_dir: "caa/generation_results/corrigible-less/mistral/6"
apply_type: "base"