# Model
id: "mistral-7b-all-sequence-0_75"
model_name_or_path: "/kaggle/input/notebooks/diansss/mistral-loader/Mistral-7B-Instruct-v0.3"
behavior: "wealth-seeking"
total_layer: 32
layer: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

# Vector
vec_dir: "caa/pretrained_vector/wealth-seeking/mistral/all"
answer_dir: "caa/generation_results/wealth-seeking/mistral/all-sequence-0_75"
apply_type: "sequence2"

treshold: 0.75