# Model
id: "mistral-7b-16"
model_name_or_path: "/kaggle/input/notebooks/diansss/mistral-loader/Mistral-7B-Instruct-v0.3"
behavior: "simpleliving-unethical"
total_layer: 32
layer: [16]

# Vector
vec_dir: "caa/pretrained_vector/simpleliving-unethical/mistral/all"
answer_dir: "caa/generation_results/simpleliving-unethical/mistral/16"
apply_type: "base"
