# Model
id: "mistral-7b-16"
model_name_or_path: "/kaggle/input/notebooks/dadangkw/mistral-loader/Mistral-7B-Instruct-v0.3"
behavior: "power-seeking"
layer: [16]
total_layer: 32

# Vector
vec_dir: "caa/pretrained_vector/power-seeking/mistral/16"
answer_dir: "caa/generation_results/power-seeking/mistral/16"
apply_type: "layer"